name: cython_experimentations
channels:
  - conda-forge
dependencies:
  - black
  - jupyter
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - pyaml
  - joblib
  - scipy
  - pip
  - pip:
      - --pre
      - --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
      - scikit-learn
