name: cython_experimentations
channels:
  - conda-forge
dependencies:
  - joblib
  - compilers
  - jupyter
  - numpy
  - scikit-learn
  - cython
  - matplotlib
  - seaborn
  - pandas
  - pyaml
  - scipy
  - pip
  - pip:
      - -e ./
