name: cython_experimentations
channels:
  - conda-forge
dependencies:
  - python=3.9
  - compilers
  - joblib
  - jupyter
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - pyaml
  - pip
  - pip:
      - --pre
      - --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
      - scikit-learn
      # Install pdist_agregation from source
      - -e ./
