pairwise_dist:
  name: pairwise_dist
  functions:
    - implementation: cython
      source: pdist.pairwise_dist
    - implementation: scipy
      source: scipy.spatial.distance.cdist
    - implementation: sklearn sequential
      source: sklearn.metrics.pairwise_distances
      params:
        metric:
          - l1
        n_jobs:
          - 1
    - implementation: sklearn parallel
      source: sklearn.metrics.pairwise_distances
      params:
        metric:
          - l1
        n_jobs:
          - -1
  datasets:
    - generator: numpy.random.rand
      n_samples: 1000
      n_features: 2
    - generator: numpy.random.rand
      n_samples: 1000
      n_features: 10
    - generator: numpy.random.rand
      n_samples: 1000
      n_features: 100
    - generator: numpy.random.rand
      n_samples: 1000
      n_features: 1000
    - generator: numpy.random.rand
      n_samples: 10_000
      n_features: 2
    - generator: numpy.random.rand
      n_samples: 10_000
      n_features: 10
    - generator: numpy.random.rand
      n_samples: 10_000
      n_features: 100
    - generator: numpy.random.rand
      n_samples: 10_000
      n_features: 1000
