pairwise_dist:
  functions:
    - implementation: Pairwise distances in Cython
      source: src.implementations.pairwise_dist
    - implementation: Scipy's cdist
      source: scipy.spatial.distance.cdist
  datasets:
    - generator: numpy.random.rand
      n_samples: 1000
      n_features: 2
    - generator: numpy.random.rand
      n_samples: 1000
      n_features: 100
    - generator: numpy.random.rand
      n_samples: 10000
      n_features: 100
    - generator: numpy.random.rand
      n_samples: 10000
      n_features: 1000
